<?php
$mime_types = array(
	'.docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
	'.doc' => 'application/msword',
	'.dot' => 'application/msword',
	'.m' => 'text/plain',
	'.m' => 'text/x-m',
	'.pdf' => 'application/pdf',
	'.pl' => 'text/plain',
	'.pot' => 'application/mspowerpoint',
	'.pot' => 'application/vnd.ms-powerpoint',
	'.ppa' => 'application/vnd.ms-powerpoint',
	'.pps' => 'application/mspowerpoint',
	'.pps' => 'application/vnd.ms-powerpoint',
	'.ppt' => 'application/mspowerpoint',
	'.ppt' => 'application/powerpoint',
	'.ppt' => 'application/vnd.ms-powerpoint',
	'.ppt' => 'application/x-mspowerpoint',
	'.ppz' => 'application/mspowerpoint',
	'.rt' => 'text/richtext',
	'.rt' => 'text/vnd.rn-realtext',
	'.rtf' => 'application/rtf',
	'.rtf' => 'application/x-rtf',
	'.rtf' => 'text/richtext',
	'.texi' => 'application/x-texinfo',
	'.texinfo' =>' lication/x-texinfo',
	'.text' => 'application/plain',
	'.text' => 'text/plain',
	'.txt' => 'text/plain',
	'txt' => 'inode/x-empty',
	'.xl' => 'application/excel',
	'.xla' => 'application/excel',
	'.xla' => 'application/x-excel',
	'.xla' => 'application/x-msexcel',
	'.xlb' => 'application/excel',
	'.xlb' => 'application/vnd.ms-excel',
	'.xlb' => 'application/x-excel',
	'.xlc' => 'application/excel',
	'.xlc' => 'application/vnd.ms-excel',
	'.xlc' => 'application/x-excel',
	'.xld' => 'application/excel',
	'.xld' => 'application/x-excel',
	'.xlk' => 'application/excel',
	'.xlk' => 'application/x-excel',
	'.xll' => 'application/excel',
	'.xll' => 'application/vnd.ms-excel',
	'.xll' => 'application/x-excel',
	'.xlm' => 'application/excel',
	'.xlm' => 'application/vnd.ms-excel',
	'.xlm' => 'application/x-excel',
	'.xls' => 'application/excel',
	'.xls' => 'application/vnd.ms-excel',
	'.xls' => 'application/x-excel',
	'.xls' => 'application/x-msexcel',
	'.xlt' => 'application/excel',
	'.xlt' => 'application/x-excel',
	'.xlv' => 'application/excel',
	'.xlv' => 'application/x-excel',
	'.xlw' => 'application/excel',
	'.xlw' => 'application/vnd.ms-excel',
	'.xlw' => 'application/x-excel',
	'.xlw' => 'application/x-msexcel',
	'.xm' => 'audio/xm',
	'.xml' => 'application/xml',
	'.xml' => 'text/xml',
);

// var_dump(array_search("application/zip",$mime_types,true));
// foreach ($mime_types as $key) {
// 	echo $key . "<br>";
// }
?>
